apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: es
  labels:
    application: logging
    component: kibana
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    component: kibana
