apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: es
  labels:
    application: logging
    component: logstash
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        application: logging
        component: logstash
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: logstash
        imagePullPolicy: IfNotPresent
        image: docker.geexfinance.com/logstash/logstash-oss:6.2.3
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-udp
          protocol: UDP
        - containerPort: 5044
          name: beats-tcp
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/ogstash.ymll
          subPath: logstash.yml
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config
        configMap:
          name: logstash-config
      - name: pipeline
        configMap:
          name: logstash-config
      restartPolicy: Always
      imagePullSecrets:
        - name: geexregistrykey
