apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logstash
  namespace: es
  labels:
    application: logging
    component: logstash
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: logstash
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
