apiVersion: v1
kind: Service
metadata:
  name: logstash-beats-tcp
  namespace: es
  labels:
    application: logging
    component: logstash
spec:
  type: ClusterIP
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
    name: logstash-beats-tcp
  selector:
    component: logstash
