apiVersion: v1
kind: Service
metadata:
  name: logstash-syslog-udp
  namespace: es
  labels:
    application: logging
    component: logstash
spec:
  type: ClusterIP
  ports:
  - port: 514
    targetPort: 514
    protocol: UDP
    name: logstash-syslog-udp
  selector:
    component: logstash
